part of '../app_theme.dart';

ThemeData _darkThemeData({String? fontFamily}) => ThemeData(
      useMaterial3: true,
      primaryColor: DarkStyleConstants.primary,
      unselectedWidgetColor: DarkStyleConstants.primaryVariant,
      appBarTheme: AppBarTheme(
        elevation: 0,
        iconTheme: const IconThemeData(
          color: DarkStyleConstants.white,
          size: 18,
        ),
        titleTextStyle: TextStyle(
          fontWeight: FontWeight.w500,
          fontStyle: FontStyle.normal,
          fontVariations: FontVariantConfigs.w500,
          fontFamily: fontFamily,
          fontSize: 20,
          color: DarkStyleConstants.primaryVariant,
        ),
        backgroundColor: DarkStyleConstants.primary,
      ),
      buttonTheme: ButtonThemeData(
        colorScheme: _colorSchemeDark,
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(12),
        ),
      ),
      outlinedButtonTheme: OutlinedButtonThemeData(
        style: OutlinedButton.styleFrom(
          elevation: 4,
          foregroundColor: _colorSchemeDark.primary,
          backgroundColor: _colorSchemeDark.surface,
          side: BorderSide(
            color: _colorSchemeDark.surface,
            width: 0,
          ),
          shadowColor: _colorSchemeDark.background,
          padding: const EdgeInsets.all(20),
          shape: RoundedRectangleBorder(
            side: BorderSide(
              color: _colorSchemeDark.surface,
              width: 0,
            ),
            borderRadius: BorderRadius.circular(12),
          ),
        ),
      ),
      textTheme: TextTheme(
        displayLarge: TextStyle(
          fontWeight: FontWeight.w300,
          fontStyle: FontStyle.normal,
          fontVariations: FontVariantConfigs.w300,
          fontFamily: fontFamily,
          fontSize: 96,
          letterSpacing: -1.5,
          color: DarkStyleConstants.primary,
        ),
        displayMedium: TextStyle(
          fontWeight: FontWeight.w300,
          fontStyle: FontStyle.normal,
          fontVariations: FontVariantConfigs.w300,
          fontFamily: fontFamily,
          fontSize: 60,
          letterSpacing: -0.5,
          color: DarkStyleConstants.primary,
        ),
        displaySmall: TextStyle(
          fontWeight: FontWeight.w400,
          fontStyle: FontStyle.normal,
          fontVariations: FontVariantConfigs.w400,
          fontFamily: fontFamily,
          fontSize: 48,
          letterSpacing: 0,
          color: DarkStyleConstants.primary,
        ),
        headlineMedium: TextStyle(
          fontWeight: FontWeight.w400,
          fontStyle: FontStyle.normal,
          fontVariations: FontVariantConfigs.w400,
          fontFamily: fontFamily,
          fontSize: 34,
          letterSpacing: 0.25,
          color: DarkStyleConstants.white,
        ),
        headlineSmall: TextStyle(
          fontWeight: FontWeight.w400,
          fontStyle: FontStyle.normal,
          fontVariations: FontVariantConfigs.w400,
          fontFamily: fontFamily,
          fontSize: 24,
          letterSpacing: 0,
          color: DarkStyleConstants.white,
        ),
        titleLarge: TextStyle(
          fontWeight: FontWeight.w500,
          fontStyle: FontStyle.normal,
          fontVariations: FontVariantConfigs.w500,
          fontFamily: fontFamily,
          fontSize: 20,
          letterSpacing: 0.15,
          color: DarkStyleConstants.white,
        ),
        titleMedium: TextStyle(
          fontWeight: FontWeight.w400,
          fontStyle: FontStyle.normal,
          fontVariations: FontVariantConfigs.w400,
          fontFamily: fontFamily,
          fontSize: 16,
          letterSpacing: 0.15,
          color: DarkStyleConstants.primary,
        ),
        titleSmall: TextStyle(
          fontWeight: FontWeight.w500,
          fontStyle: FontStyle.normal,
          fontVariations: FontVariantConfigs.w500,
          fontFamily: fontFamily,
          fontSize: 14,
          letterSpacing: 0.1,
          color: DarkStyleConstants.primary,
        ),
        bodyLarge: TextStyle(
          fontWeight: FontWeight.w400,
          fontStyle: FontStyle.normal,
          fontVariations: FontVariantConfigs.w400,
          fontFamily: fontFamily,
          fontSize: 16,
          letterSpacing: 0.5,
          color: DarkStyleConstants.primary,
        ),
        bodyMedium: TextStyle(
          fontWeight: FontWeight.w400,
          fontStyle: FontStyle.normal,
          fontVariations: FontVariantConfigs.w400,
          fontFamily: fontFamily,
          fontSize: 14,
          letterSpacing: 0.25,
          color: DarkStyleConstants.primary,
        ),
        labelLarge: TextStyle(
          fontWeight: FontWeight.w500,
          fontStyle: FontStyle.normal,
          fontVariations: FontVariantConfigs.w500,
          fontFamily: fontFamily,
          fontSize: 14,
          letterSpacing: 1.25,
          color: DarkStyleConstants.primary,
        ),
        bodySmall: TextStyle(
          fontWeight: FontWeight.w500,
          fontStyle: FontStyle.normal,
          fontVariations: FontVariantConfigs.w500,
          fontFamily: fontFamily,
          fontSize: 12,
          letterSpacing: 0.4,
          color: DarkStyleConstants.primary,
        ),
        labelSmall: TextStyle(
          fontWeight: FontWeight.w500,
          fontStyle: FontStyle.normal,
          fontVariations: FontVariantConfigs.w500,
          fontFamily: fontFamily,
          fontSize: 10,
          letterSpacing: 1.5,
          color: DarkStyleConstants.primary,
        ),
      ),
      floatingActionButtonTheme: FloatingActionButtonThemeData(
        foregroundColor: CustomDesigns.dark().main.tone100,
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(200),
        ),
      ),
      tabBarTheme: TabBarTheme(
        labelPadding: const EdgeInsets.symmetric(vertical: 8),
        labelStyle: TextStyle(
          color: CustomDesigns.dark().dark.tone500,
          fontWeight: FontWeight.w600,
          fontSize: 16,
        ),
        unselectedLabelStyle: TextStyle(
          color: CustomDesigns.dark().dark.tone300,
          fontWeight: FontWeight.w400,
          fontSize: 16,
        ),
      ),
      scaffoldBackgroundColor: DarkStyleConstants.background,
      dividerColor: DarkStyleConstants.primary,
      canvasColor: DarkStyleConstants.white,
      extensions: [
        CustomDesigns.dark(),
      ],
      colorScheme: _colorSchemeDark.copyWith(
        background: DarkStyleConstants.background,
      ),
    );

const _colorSchemeDark = ColorScheme.dark(
  brightness: Brightness.dark,
  primary: DarkStyleConstants.primary,
  onPrimary: DarkStyleConstants.black,
  secondary: DarkStyleConstants.secondary,
  background: DarkStyleConstants.background,
  surface: DarkStyleConstants.surface,
);
